package com.nashlincoln.blink.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ATTRIBUTE_TYPE.
 */
public class AttributeType {

    private Long id;
    private String description;
    private String dataType;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public AttributeType() {
    }

    public AttributeType(Long id) {
        this.id = id;
    }

    public AttributeType(Long id, String description, String dataType) {
        this.id = id;
        this.description = description;
        this.dataType = dataType;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDataType() {
        return dataType;
    }

    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
