package com.nashlincoln.blink.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ATTRIBUTE_TYPE.
 */
public class AttributeType {

    private Long id;
    private String description;
    private String dataType;

    // KEEP FIELDS - put your custom fields here
    public static final long ATTRIBUTE_On_Off = 1;
    public static final long ATTRIBUTE_Level = 2;
    public static final long ATTRIBUTE_LockState = 5;
    public static final long ATTRIBUTE_LockType = 6;
    public static final long ATTRIBUTE_ActuatorEnabled = 7;
    public static final long ATTRIBUTE_DoorState = 8;
    public static final long ATTRIBUTE_DoorOpenEvents = 9;
    public static final long ATTRIBUTE_DoorClosedEvents = 10;
    public static final long ATTRIBUTE_OpenPeriod = 11;
    public static final long ATTRIBUTE_LockDoor = 12;
    public static final long ATTRIBUTE_UnlockDoor = 13;
    // KEEP FIELDS END

    public AttributeType() {
    }

    public AttributeType(Long id) {
        this.id = id;
    }

    public AttributeType(Long id, String description, String dataType) {
        this.id = id;
        this.description = description;
        this.dataType = dataType;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDataType() {
        return dataType;
    }

    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
