package com.nashlincoln.blink.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table TIMER.
 */
public class Timer {

    private String name;
    private String time;
    private Boolean repeat;
    private Integer repeatFlags;
    private Long id;
    private Long attributableId;
    private String attributableType;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Timer() {
    }

    public Timer(Long id) {
        this.id = id;
    }

    public Timer(String name, String time, Boolean repeat, Integer repeatFlags, Long id, Long attributableId, String attributableType) {
        this.name = name;
        this.time = time;
        this.repeat = repeat;
        this.repeatFlags = repeatFlags;
        this.id = id;
        this.attributableId = attributableId;
        this.attributableType = attributableType;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public Boolean getRepeat() {
        return repeat;
    }

    public void setRepeat(Boolean repeat) {
        this.repeat = repeat;
    }

    public Integer getRepeatFlags() {
        return repeatFlags;
    }

    public void setRepeatFlags(Integer repeatFlags) {
        this.repeatFlags = repeatFlags;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAttributableId() {
        return attributableId;
    }

    public void setAttributableId(Long attributableId) {
        this.attributableId = attributableId;
    }

    public String getAttributableType() {
        return attributableType;
    }

    public void setAttributableType(String attributableType) {
        this.attributableType = attributableType;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
